import Head from "next/head";
import { Product, Dependency, WalletSection } from "../components";
import { dependencies, products } from "../config";
import { useTheme } from "../contexts/theme";
import { MoonIcon, SunIcon } from "@heroicons/react/24/outline";
import Link from "next/link";
import Image from "next/image";

export default function Home() {
  const chainName = process.env.NEXT_PUBLIC_CHAIN ?? "stargaze";

  return (
    <div className="max-w-6xl py-10 mx-6 lg:mx-auto  max-h-[100vh] overflow-y-hidden">
      <Head>
        <title>Create Cosmos App</title>
        <meta name="description" content="Generated by create cosmos app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-row justify-end items-center mb-4"></div>
      <div className="text-center">
        <div className="flex w-full justify-center text-2xl font-bold sm:text-3xl md:text-3xl">
          <Image src="/logo_landing.png" width={230} height={62} />
        </div>
      </div>

      <div className="container flex w-full mt-10">
        <div className="w-1/2">
          <Image src="/shirt_image.png" width={1000} height={1000} />
        </div>
        <div className="w-1/2 flex flex-col justify-evenly">
          <div className="mt-20 flex w-full text-center text-2xl text-white justify-evenly">
            500 $SHIRT. Printed with the memes<br></br> and profile pictures of
            cosmonauts
          </div>

          <div className="container flex flex-col w-full mt-10">
            <button className="w-full bg-[#e00036] py-2.5 rounded-md text-xl">
              SIGN THE SHIRT
            </button>
          </div>

          <div className="mt-5 flex flex-col w-full text-center justify-center text-md text-gray-400 ">
            <div className="my-3">
              Airdroping 100 $SHIRT to the Top 100 in order of{" "}
            </div>
            <div className="my-3">
              delegations to <u>Interchain.FM</u> stakers on Osmosis.
            </div>
            <div className="my-3 text-lg">
              <span className="text-gray-500">DELEGATE </span>
              <span>OSMOSIS • CANTO • UMEE • ATOM</span>
            </div>
          </div>
        </div>
      </div>

      <div className="text-sm text-center bg-black min-h-[100vh] ">
        <div className="flex flex-col">
          <div className="mt-5 text-gray-500 text-lg ">
            COMING TO OSMOSIS • MAY 1 • BLOCK 9,418,398
          </div>
          <div className="mt-10 flex justify-evenly">
            <div className="text-2xl text-[rgb(128,153,212)]">
              01<br></br>
              <b>DAYS</b>
            </div>
            <div className="text-2xl  text-[rgb(128,153,212)]">
              03<br></br>
              <b>HRS</b>
            </div>
            <div className="text-2xl  text-[rgb(128,153,212)]">
              01<br></br>
              <b>MINS</b>
            </div>
            <div className="text-2xl  text-[rgb(128,153,212)]">
              01<br></br>
              <b>SEC</b>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
