import Head from "next/head";
import { Product, Dependency, WalletSection } from "../components";
import { dependencies, products } from "../config";
import { useTheme } from "../contexts/theme";
import { MoonIcon, SunIcon } from "@heroicons/react/24/outline";
import Link from "next/link";
import Image from "next/image";

export default function Home() {
  const chainName = process.env.NEXT_PUBLIC_CHAIN ?? "stargaze";

  return (
    <div className="max-w-6xl py-10 mx-6 lg:mx-auto min-h-[100vh] overflow-y-hidden">
      <Head>
        <title>Suitdrop | Home</title>
        <meta name="description" content="Generated by create cosmos app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="flex flex-row justify-end items-center mb-2 gap-5">
        <Link
          className="inline-flex items-center justify-center w-12 h-12 text-black border rounded-lg dark:text-white hover:bg-black/10 dark:hover:bg-white/10 border-black/10 dark:border-white/10 mr-2"
          href="/redeem"
        >
          <div className="hover:underline hover:underline-offset-1 text-[#e0e0e0] hover:text-white mr-2 text-lg cursor-pointer">
            Redeem
          </div>
        </Link>
        <WalletSection />
      </div>
      <div className="text-center">
        <div className="flex relative w-full justify-center text-2xl font-bold sm:text-3xl md:text-3xl">
          <Image src="/logo_landing.png" width={230} height={62} />
        </div>
      </div>

      <div className="container flex flex-col md:flex-row w-full mt-10 mx-auto">
        <div className="w-full md:w-1/2 flex justify-center text-center">
          <Image src="/shirt_image.png" width={1000} height={1000} />
        </div>
        <div className="w-full md:w-1/2 flex flex-col justify-evenly">
          <div className="mt-20 flex w-full text-2xl text-white justify-start text-left">
            500 $SHIRT. Printed with the memes<br></br> and profile pictures of
            cosmonauts
          </div>

          <div className="container flex flex-col w-full mt-10">
            <button className="w-full bg-[#e00036] py-2.5 rounded-md text-xl micro-font">
              SIGN THE SHIRT
            </button>
          </div>

          <div className="mt-5 flex flex-col w-full text-center justify-center text-md text-gray-400 ">
            <div className="my-1">
              Airdroping 100 $SHIRT to the Top 100 in order of{" "}
            </div>
            <div className="my-1">
              delegations to <u>Interchain.FM</u> stakers on Osmosis.
            </div>
            <div className="my-2 text-lg">
              <span className="text-gray-500">DELEGATE </span>
              <span>OSMOSIS • CANTO • UMEE • ATOM</span>
            </div>
          </div>
        </div>
      </div>

      <div className="text-sm text-center bg-black min-h-[200px] ">
        <div className="flex flex-col">
          <div className="mt-5 text-gray-500 text-md" style={{ letterSpacing: '5px' }}>
            COMING TO OSMOSIS • MAY 1 • BLOCK 9,418,398
          </div>
          <div className="mt-10 flex justify-evenly">
            <div className="text-[rgb(128,153,212)] micro-font">
              <span className="text-2xl">01</span><br></br>
              <b className="text-lg">DYS</b>
            </div>
            <div className=" text-[rgb(128,153,212)] micro-font">
              <span className="text-2xl">03</span><br></br>
              <b className="text-lg">HRS</b>
            </div>
            <div className=" text-[rgb(128,153,212)] micro-font">
              <span className="text-2xl">16</span><br></br>
              <b className="text-lg">MINS</b>
            </div>
            <div className=" text-[rgb(128,153,212)] micro-font">
              <span className="text-2xl">26</span><br></br>
              <b className="text-lg">SEC</b>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
