import Head from "next/head";
import { Product, Dependency, WalletSection } from "../components";
import Link from "next/link";
import Image from "next/image";
import Modal from "react-modal";
import { useState, useEffect } from "react";
import { AiOutlineCloseCircle } from "react-icons/ai";
import ReactLoading from 'react-loading';
import { storefront } from "../utils/storefront";
import productHelper from "../utils/productHelper";
import { useSigningClient } from "../contexts/cosmwasm";
import { numberWithCommas } from "../utils/utils";
import styles from "../styles/layout.module.scss";

Modal.setAppElement("#__next");
const PUBLIC_DENOM = process.env.NEXT_PUBLIC_DENOM;

export default function Redeem() {
  const chainName = process.env.NEXT_PUBLIC_CHAIN ?? "stargaze";
  const [modalIsOpen, setModalIsOpen] = useState(false);
  const [redeemAmount, setRedeemAmount] = useState(0);
  const [shirt, setShirt] = useState(null);
  const { balances }: any = useSigningClient();

  const getShirt = async () => {
    const { body } = await storefront();
    const mappedProducts = body
      ? (body as any).products.edges.map((p) => {
        return productHelper.map(p.node);
      })
      : [];
    const sku = "shirtdrop";
    const shirt = productHelper.getBySKU(sku, mappedProducts);
    setShirt(shirt[0]);
  };

  useEffect(() => {
    getShirt();
  }, []);

  return (
    <div className="max-w-6xl py-10 mx-6 lg:mx-auto max-h-[100vh] overflow-y-hidden">
      <Head>
        <title>Suitdrop | Redeem</title>
        <meta name="description" content="Generated by create cosmos app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="flex flex-row justify-end items-center mb-2 gap-5">
        <Link
          className="inline-flex items-center justify-center w-12 h-12 text-black border rounded-lg dark:text-white hover:bg-black/10 dark:hover:bg-white/10 border-black/10 dark:border-white/10 mr-2"
          href="/"
        >
          <div className="hover:underline hover:underline-offset-1 text-[#e0e0e0] hover:text-white mr-2 text-lg cursor-pointer">
            Claim Airdrop
          </div>
        </Link>
        <WalletSection />
      </div>
      <div className="text-center">
        <h1 className="text-2xl font-bold sm:text-3xl md:text-3xl">
          <Image src="/shirtdrop.svg" width={230} height={62} />
        </h1>
      </div>

      <div className="container flex w-full mt-10">
        <div className="w-1/2">
          {shirt ? (
            <Image
              src={shirt.image.src}
              height={shirt.image.height}
              width={shirt.image.width}
              alt={shirt.title}
            />
          ) :
            <div className="flex flex-col gap-4 justify-center items-center h-full min-h-[500px]">
              <ReactLoading type="spin" color="#fff" />
              <span className="text-white text-lg">Loading...</span>
            </div>
          }
        </div>
        <div className="w-1/2 flex flex-col justify-evenly">
          <div className="flex w-full text-center justify-center text-2xl">
            SELECT SIZE:
          </div>
          <div className="mt-5 flex w-full text-center text-2xl text-gray-400 justify-evenly">
            {shirt?.options.map((o) => {
              return (
                <div key={o.name} className={styles.option}>
                  <span>{o.name}:</span>
                  {o.values.map((v) => {
                    return <button key={v}>{v}</button>;
                  })}
                </div>
              );
            })}
          </div>
          <div className="mt-5 flex w-full text-center justify-center text-2xl">
            DESCRIPTION
          </div>
          <div
            className="mt-5 flex flex-col w-full text-center justify-center text-lg"
            dangerouslySetInnerHTML={{ __html: shirt?.description }}
          >
          </div>

          <div className="container flex flex-col w-full mt-10 mb-5">
            <a href="https://osmosis.zone/" target="_blank" rel="noreferrer">
              <button className="w-full bg-[#e00036] hover:bg-[#ad062e] transition py-2.5 rounded-md text-xl">
                BUY $SHIRT
              </button>
            </a>
            <button
              className="mt-5 w-full bg-gray-500 hover:bg-gray-600 transition p-2.5 rounded-md text-xl"
              onClick={() => setModalIsOpen(true)}
              disabled={!shirt}
            >
              REDEEM
            </button>
          </div>
        </div>
      </div>

      <div className="flex justify-center  text-sm text-center bg-black min-h-[100vh] "></div>

      <Modal
        isOpen={modalIsOpen}
        onRequestClose={() => setModalIsOpen(false)}
        contentLabel="Redeem Modal"
        overlayClassName="bg-gray-500 bg-opacity-75 transition-opacity opacity-100"
        className="bg-gray-800 flex justify-center items-center rounded-2xl relative p-10"
      >
        <h2 className="absolute top-10 text-2xl text-white text-bold">
          REDEEM
        </h2>
        <button
          className="absolute right-5 top-5 text-md text-white text-bold"
          onClick={() => setModalIsOpen(false)}
        >
          <AiOutlineCloseCircle className="w-8 h-8" />
        </button>
        <div className="mt-10 flex flex-col w-[300px] max-w-[300px]">
          <div className="mt-2 text-gray-400 text-md text-right">
            Balance: {balances ? numberWithCommas(balances[PUBLIC_DENOM]) : 0} $OSMO
          </div>
          <input
            type="number"
            className="mt-1 text-center rounded-lg w-[300px] max-w-[300px]
            overflow-x-scroll "
            value={redeemAmount}
            onChange={(e) => setRedeemAmount(Number(e.target.value))}
          />
          <div className="mt-2 text-gray-400 text-md">
            You will send {redeemAmount} $OSMO to the treasury.
          </div>
          <button className="mt-10 text-lg w-full bg-[#e00036] rounded-xl py-2 text-[#e0e0e0] hover:text-white border-2 border-gray-800 hover:border-white ">
            Confirm
          </button>
        </div>
      </Modal>
    </div>
  );
}
