import Head from "next/head";
import { Product, Dependency, WalletSection } from "../components";
import { dependencies, products } from "../config";
import { useTheme } from "../contexts/theme";
import { MoonIcon, SunIcon } from "@heroicons/react/24/outline";
import Link from "next/link";
import Image from "next/image";
import Modal from "react-modal";
import { useState } from "react";
import { AiOutlineCloseCircle } from "react-icons/ai";

Modal.setAppElement("#__next");

export default function Home() {
  const chainName = process.env.NEXT_PUBLIC_CHAIN ?? "stargaze";
  const [modalIsOpen, setModalIsOpen] = useState(false);
  const [redeemAmount, setRedeemAmount] = useState(0);

  return (
    <div className="max-w-6xl py-10 mx-6 lg:mx-auto max-h-[100vh] overflow-y-hidden">
      <Head>
        <title>Create Cosmos App</title>
        <meta name="description" content="Generated by create cosmos app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-row justify-end items-center mb-4">
        <Link
          className="inline-flex items-center justify-center w-12 h-12 text-black border rounded-lg dark:text-white hover:bg-black/10 dark:hover:bg-white/10 border-black/10 dark:border-white/10 mr-2"
          href="/"
        >
          <div className="hover:underline hover:underline-offset-1 text-[#e0e0e0] hover:text-white mr-2">
            Claim Airdrop
          </div>
        </Link>
        <WalletSection />
      </div>
      <div className="text-center">
        <h1 className="text-2xl font-bold sm:text-3xl md:text-3xl">
          SHIRTDROP
        </h1>
      </div>

      <div className="container flex w-full mt-10">
        <div className="w-1/2">
          <Image src="/shirt_image.png" width={1000} height={1000} />
        </div>
        <div className="w-1/2 flex flex-col justify-evenly">
          <div className="flex w-full text-center justify-center text-2xl">
            SELECT SIZE:
          </div>
          <div className="mt-5 flex w-full text-center text-2xl text-gray-400 justify-evenly">
            <span>S</span>
            <span>M</span>
            <span>L</span>
            <span>XL</span>
            <span>2XL</span>
          </div>
          <div className="mt-5 flex w-full text-center justify-center text-2xl">
            DESCRIPTION
          </div>
          <div className="mt-5 flex flex-col w-full text-center justify-center text-lg">
            <div className="my-3">PRIVATE LEVEL S102 FEE</div>
            <div className="my-3">SUBLIMATION BLEND, SLIM FIT</div>
            <div className="my-3">35/65 POLYSTER / RAYON JERSEY</div>
          </div>

          <div className="container flex flex-col w-full mt-10 mb-5">
            <a href="https://osmosis.zone/" target="_blank" rel="noreferrer">
              <button className="w-full bg-[#e00036] hover:bg-[#ad062e] transition py-2.5 rounded-md text-xl">
                BUY $SHIRT
              </button>
            </a>
            <button
              className="mt-5 w-full bg-gray-500 hover:bg-gray-600 transition p-2.5 rounded-md text-xl"
              onClick={() => setModalIsOpen(true)}
            >
              REDEEM
            </button>
          </div>
        </div>
      </div>

      <div className="flex justify-center  text-sm text-center bg-black min-h-[100vh] "></div>

      <Modal
        isOpen={modalIsOpen}
        onRequestClose={() => setModalIsOpen(false)}
        contentLabel="Example Modal"
        className="bg-gray-800 flex justify-center items-center w-[25vw] h-[18vw] rounded-2xl relative"
      >
        <h2 className="absolute top-10 text-2xl text-white text-bold">
          REDEEM
        </h2>
        <button
          className="absolute right-5 top-5 text-md text-white text-bold"
          onClick={() => setModalIsOpen(false)}
        >
          <AiOutlineCloseCircle className="w-8 h-8" />
        </button>
        <div className="mt-10 flex flex-col w-[300px] max-w-[300px]">
          <div className="mt-2 text-gray-400 text-md text-right">
            Balance: {100} $OSMO
          </div>
          <input
            type="number"
            className="mt-1 text-center rounded-lg w-[300px] max-w-[300px]
            overflow-x-scroll "
            value={redeemAmount}
            onChange={(e) => setRedeemAmount(Number(e.target.value))}
          />
          <div className="mt-2 text-gray-400 text-md">
            You will send {redeemAmount} $OSMO to the treasury.
          </div>
          <button className="mt-10 text-lg w-full bg-[#e00036] rounded-xl py-2 text-[#e0e0e0] hover:text-white border-2 border-gray-800 hover:border-white ">
            Confirm
          </button>
        </div>
      </Modal>
    </div>
  );
}
